name: docs-check

on:
  push:
  pull_request:

jobs:
  ensure-readmes-updated:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check docs updated when code changes
        shell: bash
        run: |
          set -euo pipefail
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          else
            BASE_SHA=$(git rev-parse HEAD~1 || echo "")
            HEAD_SHA=$(git rev-parse HEAD)
            # First push to an empty branch: skip
            if [[ -z "$BASE_SHA" ]]; then
              echo "No previous commit to compare; skipping check."
              exit 0
            fi
          fi

          echo "Comparing $BASE_SHA..$HEAD_SHA"
          CHANGED=$(git diff --name-only "$BASE_SHA" "$HEAD_SHA")
          echo "Changed files:\n$CHANGED"

          # Identify code changes (excluding docs)
          CODE_CHANGED=$(echo "$CHANGED" | grep -E '^(backend|frontend)/|^package\.json$|^package-lock\.json$' || true)
          DOCS_CHANGED=$(echo "$CHANGED" | grep -E '^README\.md$|^README-TH\.md$' || true)

          if [[ -n "$CODE_CHANGED" && -z "$DOCS_CHANGED" ]]; then
            echo "Error: Code or configuration changed, but README.md/README-TH.md were not updated."
            echo "Please update both READMEs to reflect these changes."
            exit 1
          fi

          echo "Docs check passed."

